value = int(input())
print(value)
value = divmod(value, 100)
print('%i nota(s) de R$ 100,00' %(value[0]))
value = divmod(value[1], 50)
print('%i nota(s) de R$ 50,00' %(value[0]))
value = divmod(value[1], 20)
print('%i nota(s) de R$ 20,00' %(value[0]))
value = divmod(value[1], 10)
print('%i nota(s) de R$ 10,00' %(value[0]))
value = divmod(value[1], 5)
print('%i nota(s) de R$ 5,00' %(value[0]))
value = divmod(value[1], 2)
print('%i nota(s) de R$ 2,00' %(value[0]))
print('%i nota(s) de R$ 1,00' %(value[1]))
