
value =  float(input())
print('NOTAS:')
value = divmod(value, 100)
print('%i nota(s) de R$ 100.00' %(value[0]))
value = divmod(value[1], 50)
print('%i nota(s) de R$ 50.00' %(value[0]))
value = divmod(value[1], 20)
print('%i nota(s) de R$ 20.00' %(value[0]))
value = divmod(value[1], 10)
print('%i nota(s) de R$ 10.00' %(value[0]))
value = divmod(value[1], 5)
print('%i nota(s) de R$ 5.00' %(value[0]))
value = divmod(value[1], 2)
print('%i nota(s) de R$ 2.00' %(value[0]))
print('MOEDAS:')
value = divmod(value[1], 1)
print('%i moeda(s) de R$ 1.00' %(value[0]))
value = int(round(value[1] * 100))
value = divmod(value, 50)
print('%i moeda(s) de R$ 0.50' %(value[0]))
value = divmod(value[1], 25)
print('%i moeda(s) de R$ 0.25' %(value[0]))
value = divmod(value[1], 10)
print('%i moeda(s) de R$ 0.10' %(value[0]))
value = divmod(value[1], 5)
print('%i moeda(s) de R$ 0.05' %(value[0]))
print('%i moeda(s) de R$ 0.01' %(value[1]))

